language: python

python:
  - "3.6"
  
install:
- python -m pip install --upgrade pip
- pip install --upgrade pip
- pip install git+git://github.com/jwaschkau/pyrtf
- pip install -r requrement.txt

script: python manage.py test --verbosity 2