# Generated by Django 2.1.3 on 2018-11-27 17:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('loaded_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to=api.models.get_file_path)),
            ],
        ),
    ]
