# Generated by Django 2.1.3 on 2018-11-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='owner',
        ),
    ]
