# Generated by Django 2.1.3 on 2018-12-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20181205_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='date_train',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
