# Generated by Django 2.1.3 on 2018-12-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181205_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='train_data_name',
            new_name='train_data_file_name',
        ),
    ]
