# Generated by Django 2.1.3 on 2018-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181205_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='date_train',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
